# Generated by Django 3.2.9 on 2021-11-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corp_code', models.CharField(max_length=100)),
                ('stock_code', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('modify_date', models.DateTimeField()),
            ],
        ),
    ]
